name: svcgui_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - numpy
    - pandas
    - ffmpeg
    - tensorflow
    - torch
    - torchvision
    - torchaudio
    - tkinter
